### ISSUE TITLE
Upgrade guzzle 7

### ISSUE THREAD

**Issue by joovence** [eversign/eversign-php-sdk#31]
Upgrading to [Laravel 8](https://laravel.com/docs/8.x/upgrade#updating-dependencies) requires upgrading `guzzlehttp/guzzle` to `^7.0.1`

Are you planning to [upgrade](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md)?

Thank you

**Comment by joovence** [comment]
Found out `^7.0.1` is not really required...

https://laracasts.com/discuss/channels/laravel/guzzlehttp-error-while-upgrading-laravel-to-8-from-7?page=1

You can close you're not planning to upgrade.

**Comment by milanlatinovic** [comment]
Hi @joovence,

Firstly, thank you for reporting this. Also, thank you for finding a workaround and sharing it here.

We do intend to keep our SDK in updated condition. However, we do not upgrade to major (breaking) changes in dependencies unless there is no strong reason. Our SDK is used by a bigger community and we are trying to support everyone. 

I will close this issue because you found out that guzzlehttp/guzzle to ^7.0.1 is not mandatory for Laravel 8.

However, if you experience that any SDK dependency is stopping you from working, please report it to us in one new issue.

Thank you!
