### ISSUE TITLE
Language not supported error using 'pt' identifier on setLanguage

### ISSUE THREAD

**Issue by bsandr** [eversign/eversign-php-sdk#32]

**Comment by milanlatinovic** [comment]
Dear @bsandr, firstly thank you for reporting this issue to us. However, in order to help SDK community and our Eversign team support this as good as possible, please describe issue in more details (ideally using our Template Issues). Right now your issue has "no description provided". 

For example, you can provide part of the code, exact call that you were making. In short, anything that would help us reproduce this issue so we can debug and resolve it.

For example, when I looked at the code, I see that in Config.php file, Portuguese 'pt' is missing within $AVAILABLE_LANGUAGES. We can add it and consider it supported. However, without having actual issue described from your side we can not reproduce and test this fix.

Additionally, if you want, you can include 'pt' in SDK configuration ('pt' added) and see if this resolves your issue:
```
    public static $AVAILABLE_LANGUAGES = [
        'en',
        'da',
        'nl',
        'fr',
        'de',
        'hi',
        'it',
        'pl',
        'ru',
        'es',
        'se',
        'tr',
        'pt'
    ];
```
Let me know if this works for you, so I can create a proper patch, or provide us with more details about your issue.
Thanks!

**Comment by milanlatinovic** [comment]
Hi @bsandr, I haven't received any feedback from your side. Could you confirm that proposed fix is working for you or (if it is not working) provide more details related to your issue. 

Thanks!

**Comment by milanlatinovic** [comment]
Dear @bsandr, just to let you know that this fix was confirmed and tested. 
New release of this PHP SDK is now supporting Portuguese, so you can update dependency and continue with your work.

As a small proposal from my side, when creating Issues in public SDKs, it would be beneficial for you to set "Watch" option (should be enabled by default). This would provide you with email notifications when someone responds to your thread so you can respond back. In general, this will improve quality of answers you get once you open initial and further issues.

I will mark this issue as resolved now.
Thank you for reporting this and good luck in your further work!
